# fly.toml app configuration file generated for red-tree-6803 on 2023-06-27T17:04:16+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "red-tree-6803"
primary_region = "sin"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
